In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True)

### 1-D array

#### Atributes of arrays

dtype

ndim

size

Shape

In [3]:
a= np.array([12,15,16,17])

In [4]:
a.dtype

dtype('int32')

In [5]:
a.shape

(4,)

In [6]:
a.ndim

1

In [7]:
a.size

4

In [8]:
a[0]

12

In [9]:
a[-1]

17

#### Multidimensional arrays

In [10]:
a_2d=np.array([
              [18,15,19,20],
              [20,22,33,40]
              ])

In [11]:
a_2d.size

8

In [12]:
a_2d.shape

(2, 4)

In [13]:
a_2d.ndim

2

In [14]:
a_2d[0]

array([18, 15, 19, 20])

In [15]:
a_2d[-1][3]

40

In [16]:
a_2d[-1][0]

20

In [17]:
a_2d[-1][-2]

33

#### Another type of multidimensional arrays

In [18]:
Another_array=np.array([[[10,15,18,20]]])

In [19]:
Another_array.dtype

dtype('int32')

In [20]:
Another_array.shape

(1, 1, 4)

In [21]:
Another_array.ndim

3

In [22]:
Another_array[0][0][2]

18

#### Lets change its datatype into float

In [23]:
a_2d=np.array([[15,14,13,12],[39,33,34,35]],dtype=float)

In [24]:
a_2d

array([[15., 14., 13., 12.],
       [39., 33., 34., 35.]])

#### Lets create a bigger one

In [25]:
a_bigger=np.array([
    [
        [10,15,14,10],[30,35,34,33],[66,67,68,65]],
    [
        [33,34,35,36],[44,45,46,47],[77,78,79,76]],
    [
        [10,11,12,13],[21,22,23,24],[33,34,23,22]]
         ])

In [47]:
a_bigger[1][2][1]

78

In [26]:
a_bigger.dtype

dtype('int32')

In [27]:
a_bigger.size

36

In [28]:
a_bigger.ndim

3

In [29]:
a_bigger[0][0][3]

10

#### Filling Arrays

#### np.full

In [30]:
a_full =np.full((3,5,4),"ok")

In [31]:
a_full

array([[['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok']],

       [['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok']],

       [['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok'],
        ['ok', 'ok', 'ok', 'ok']]], dtype='<U2')

In [32]:
a_full.dtype

dtype('<U2')

In [33]:
a_1=np.full((4,5,6),5)

In [34]:
a_1

array([[[5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5]]])

In [35]:
a_1.shape

(4, 5, 6)

In [36]:
a_1.ndim

3

#### Zeros and Ones

In [37]:
a_zeros = np.zeros((3,3))

In [38]:
a_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
b_one =np.ones((3,4,3))
b_one

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#### Empyy an d random

In [40]:
e=np.empty((4,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
e1=np.empty((10,11))
e1

array([[0.00000000e+000, 6.95309185e-310, 4.07110092e-321,
                    nan, 1.12646967e-321, 0.00000000e+000,
        3.77704695e+233, 7.22756687e+159, 1.10639950e+200,
        3.64726544e+180, 1.87750993e-152],
       [4.82336277e+228, 9.23528171e+242, 2.52960802e-258,
        4.47593816e-091, 1.76353931e-070, 8.63819469e-096,
        7.12930810e+159, 2.61191759e+209, 2.25020976e+223,
        1.67640691e+243, 1.24595996e-089],
       [1.74593501e+238, 1.13556093e-153, 1.96088695e+243,
        9.82391603e+252, 3.62479391e+228, 1.32655511e-258,
        7.22082943e+159, 6.03433819e-154, 2.35570319e+251,
        4.77800043e+180, 5.80426330e+180],
       [2.19980343e-152, 1.12038868e+219, 2.31881454e-152,
        6.01346953e-154, 5.82147482e+180, 6.12486739e+257,
        4.47593784e-091, 1.45291304e-094, 1.62596915e-086,
        1.43615024e+161, 6.01334682e-154],
       [2.59345433e+161, 6.72801012e+199, 9.13601355e+242,
        1.48504071e+161, 1.45913393e-152, 1.12044105e+219,
  

In [44]:
e1_random=np.random.random((2,2))
e1_random

array([[0.88822315, 0.83022185],
       [0.34595861, 0.84104338]])

In [45]:
e1_random.ndim

2

In [46]:
e1_random.size

4

#### Ranges

#### Arange

#### arguments are : strart-stop-step

In [48]:
a_arange = np.arange(10,50,5)

In [49]:
a_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

In [55]:
a_arange1=np.arange(0,20,5)
a_arange1

array([ 0,  5, 10, 15])

In [56]:
a_arrage1=np.arange(1,91,9)
a_arrage1

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82])

### linspace

In [58]:
b_linspace =np.linspace(0,50,5)
b_linspace

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [59]:
b_linspace.ndim

1

In [60]:
b_linspace.size

5

In [61]:
b_linspace.dtype

dtype('float64')

In [64]:
v=np.linspace(1,10,4,dtype=int)

In [65]:
v

array([ 1,  4,  7, 10])